language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
# Requires JDK 9 due to https://travis-ci.org/github/peter-tackage/jonty/builds/668821354 and
#  https://youtrack.jetbrains.com/issue/KT-17866
jdk:
- oraclejdk9